entry = input()
entry = entry.split(" ")
x = int(entry[0])
y = int(entry[1])
print(str(x) + " + " + str(y) + " = " + str(x + y))
print(str(x) + " * " + str(y) + " = " + str(x * y))
print(str(x) + " - " + str(y) + " = " + str(x - y))